//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Codifico.ENL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderClients
    {
        public int Orderid { get; set; }
        public Nullable<int> CustId { get; set; }
        public System.DateTime Requireddate { get; set; }
        public Nullable<System.DateTime> Shippeddate { get; set; }
        public string Shipname { get; set; }
        public string Shipaddress { get; set; }
        public string Shipcity { get; set; }
    }
}
