//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Codifico.ENL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Shippers
    {
        public int Shipperid { get; set; }
        public string Companyname { get; set; }
    }
}
